### ISSUE TITLE
Support of files with .sass, .scss Extension

### ISSUE THREAD

**Issue by olafgleba** [kevinkyang/auto-comment-blocks#3]
Hi,

support for SASS/SCSS file would be very nice. 

Cheers and thanks in advance
Olaf

**Comment by kevinkyang** [comment]
I'll look into it. Out of curiosity, as I'm not familiar with SASS - how commonly used is this style of doc comment formatting?

**Comment by olafgleba** [comment]
It is quite popular(and often recommended, s. https://cssguidelin.es/#commenting). While you have `//` to comment out single line and `/* ... */` for multiline comments in SASS, following the Javadoc standard allows to document the source code more clearly.

**Comment by kevinkyang** [comment]
Okay, I just pushed an update that adds javadoc comments to .css/.scss files. Try it out and let me know if there's any issues.

**Comment by olafgleba** [comment]
Hi, great! It would be nice if the completion after pressing the return key is identical to other languages.

Current in .scss files (after typing `/**` + press the return key):
<pre>
/**
| */</pre>

Default in other languages:
<pre>/**
 * |
 */</pre>

Thanks!

**Comment by kevinkyang** [comment]
There's definitely an issue right now where it behaves erratically. Sometimes it won't add the `*/` if you type `/**`, and sometimes I see the problem you've described. This actually can happen in C/C++ as well, but less often for me. I don't believe my code is causing this (could be wrong), so maybe there's a bug in VS Code, or there are conflicts due to the way the extension API is designed. 

I would suggest reloading your workspace and seeing if it works because that does fix it sometimes. Meanwhile I'm going to see if I can eliminate the problem, but I'm worried that the only way to fix it might be to make the extension much heavier.

**Comment by olafgleba** [comment]
Thank for your effort.
